# Use an official Python runtime as a parent image
FROM  python: 3.9 slim
# Set the working directory in the container
WORKDIR .  
# Copy the current directory contents into the container at /app
COPY <...>
# Install any needed packages specified in requirements.txt

# Make port 6000 available to the world outside this container

# Define environment variable

# Run app.py when the container launches

# End of File